---
title: "Imputation for the test file"
author: "Arnau Gómez Català"
date: "2025-10-30"
output: pdf_document
---


## MICE:

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(VIM)
data <- read_csv("test.csv", col_types = cols(...1 = col_skip()))

for(i in 1:ncol(data)){
  if(is.character(data[[i]])==TRUE){
    data[[i]] = as.factor(data[[i]])
  }
}

data$HasCrCard <- as.factor(data$HasCrCard)
data$IsActiveMember <- as.factor(data$IsActiveMember)
data$SavingsAccountFlag <- as.factor(data$SavingsAccountFlag)
```


```{r}
visdat::vis_dat(data)
```


```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
set.seed(28657)

complete_columns <- function(original, imputed) {
    out <- original
    for (col in names(imputed)) {
        out[col] <- imputed[col]
    }
    return(out)
}

#Imputació per a numeriques:

data_for_imputation_num <- data |>
  select(Tenure, Balance, TransactionFrequency, Age, NumOfProducts, ComplaintsCount, EstimatedSalary, AvgTransactionAmount, CreditScore, NetPromoterScore, DigitalEngagementScore)

mice_output_num <- mice::mice(data_for_imputation_num, method = "pmm", m = 10)
imputed_data_num <- mice::complete(mice_output_num)

data_imputed_MICE_test <- complete_columns(data, imputed_data_num)
```

```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
#Imputació per a categòriques:

data_for_imputation_fac <- data |>
  select(EducationLevel, LoanStatus, Geography, CustomerSegment, MaritalStatus)

mice_output_fac <- mice::mice(data_for_imputation_fac, method = "polyreg", m = 10)
imputed_data_fac <- mice::complete(mice_output_fac)

data_imputed_MICE_test <- complete_columns(data_imputed_MICE_test, imputed_data_fac)
```

```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}

#Imputació per a binàries:

data_for_imputation_bin <- data |>
  select(Gender, HasCrCard, IsActiveMember, SavingsAccountFlag)

mice_output_bin <- mice::mice(data_for_imputation_bin, method = "logreg", m = 10)
imputed_data_bin <- mice::complete(mice_output_bin)

data_imputed_MICE_test <- complete_columns(data_imputed_MICE_test, imputed_data_bin)

```

```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
density_before_after <- function(before, after) {
    require(ggplot2)
    
    density_df_before <- before |> 
        select(where(is.numeric)) |>
        mutate(imputation = "original")
    
    density_df_after <- after |>
        select(where(is.numeric)) |>
        mutate(imputation = "imputat")
    
    density_df <- bind_rows(density_df_before, density_df_after) |>
        mutate(imputation = factor(imputation)) |>
        tidyr::pivot_longer(!imputation, names_to = "variable") |>
        filter(!is.na(value))
    
    ggplot(density_df, aes(x = value, color = imputation, fill = imputation)) +
        facet_wrap(~variable, scales = "free") +
        geom_histogram(alpha = 0.2, width = 0.1, bins = 30, position = "dodge") +
        scale_color_discrete(aesthetics = c("color", "fill"), name = "") +
        scale_y_continuous(breaks = NULL) +
        xlab("") +
        ylab("") +
        ggtitle("Densitat abans i després de la imputació.") +
        theme_minimal() +
        theme(panel.grid = element_blank())
}
mass_before_after <- function(before, after) {
    require(ggplot2)
    
    mass_df_before <- before |>
        select(where(is.factor)) |>
        mutate(imputation = "original")
    
    mass_df_after <- after |>
        select(where(is.factor)) |>
        mutate(imputation = "imputat")
    
    levels_in_order <- lapply(mass_df_before, levels) |> unlist()
    
    mass_df <- bind_rows(mass_df_before, mass_df_after) |>
      mutate(imputation = factor(imputation)) |>
      tidyr::pivot_longer(!imputation, names_to = "variable") |>
      filter(!is.na(value)) |>
      group_by(imputation, variable) |> 
      reframe(prop = proportions(table(value)), category = names(prop)) |>
      group_by(variable) |> 
      mutate(category = factor(category, levels = levels(mass_df_before[[unique(variable)]]))) |>
      filter(prop > 0)
    
    ggplot(mass_df, aes(x = category, y = prop, color = imputation, fill = imputation)) +
        facet_wrap(~variable, scales = "free") +
        geom_col(alpha = 0.2, width = 0.6, position = "dodge") +
        scale_color_discrete(aesthetics = c("color", "fill"), name = "") +
        scale_y_continuous(breaks = NULL) +
        xlab("") +
        ylab("") +
        ggtitle("Massa abans i després de la imputació") + 
        theme_minimal() +
        theme(panel.grid = element_blank(),
              axis.text.x = element_text(angle = 45, hjust = 1))
}

```


```{r}
density_before_after(data, data_imputed_MICE_test)
```

```{r}
mass_before_after(data, data_imputed_MICE_test)
```


```{r}
save(data_imputed_MICE_test, file = "C:/Users/Asus/Desktop/Quarto/Mineria_de_Datos/Treball_Mineria_de_Dades/Bases_de_dades/data_NA_imputed_MICE_test.RData")
```


## KNN:

```{r}
data_for_imputation <- cbind(data_for_imputation_bin, data_for_imputation_fac, data_for_imputation_num) 


set.seed(28657)
imputed_data <- VIM::kNN(
    as.data.frame(data_for_imputation), 
    k = 7, imp_var = FALSE)

data_for_imputation_KNN <- cbind(data_for_imputation, data$ID, data$Surname)

data_imputed_KNN_test <- complete_columns(data_for_imputation_KNN, imputed_data)
```


```{r}
density_before_after(data, data_imputed_KNN_test)
```

```{r}
mass_before_after(data, data_imputed_KNN_test)
```


```{r}
save(data_imputed_KNN_test, file = "C:/Users/Asus/Desktop/Quarto/Mineria_de_Datos/Treball_Mineria_de_Dades/Bases_de_dades/data_NA_imputed_KNN_test.RData")
```


## Random FOREST:

```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
set.seed(28657)
forest_output <- missForest::missForest(
    as.data.frame(data_for_imputation),
    maxiter = 10, ntree = 20,
    variablewise = TRUE, verbose = TRUE, 
)

data_imputed_FOREST_test <- complete_columns(data, forest_output$ximp)
```

```{r}
density_before_after(data, data_imputed_FOREST_test)
```

```{r}
mass_before_after(data, data_imputed_FOREST_test)
```

```{r}
save(data_imputed_FOREST_test, file = "C:/Users/Asus/Desktop/Quarto/Mineria_de_Datos/Treball_Mineria_de_Dades/Bases_de_dades/data_NA_imputed_FOREST_test.RData")
```


## Imputació per Bootstrap:

Amb la funció *aregImpute()* podrem fer imputació de les dades faltants basada en regressions amb splines. Utilitza regressió aditiva amb splines per a variables numèriques i regressió logística per a les categòriques.

```{r, results=FALSE, message=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
set.seed(28657)

data_for_imputation$ComplaintsCount <- as.factor(data_for_imputation$ComplaintsCount)
data_for_imputation$NumOfProducts <- as.factor(data_for_imputation$NumOfProducts)

areg_output <- Hmisc::aregImpute(
    data = data_for_imputation,
    formula = ~ Gender + HasCrCard + IsActiveMember + SavingsAccountFlag + EducationLevel + LoanStatus + Geography + CustomerSegment + MaritalStatus + Tenure + Balance + TransactionFrequency + Age + EstimatedSalary + AvgTransactionAmount + CreditScore + NetPromoterScore + DigitalEngagementScore + ComplaintsCount + NumOfProducts,
    nk = 5
)
```


```{r, results=FALSE, message=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
imputed_data_BOOT <- areg_output$imputed
data$ComplaintsCount <- as.factor(data$ComplaintsCount)
data$NumOfProducts <- as.factor(data$NumOfProducts)
data_imputed_AREG_test <- data

for (col in names(imputed_data_BOOT)) {
  if (is.factor(data[[col]])) {
    levels_col <- levels(data[[col]])
    data_imputed_AREG_test[[col]][is.na(data[[col]])] <- 
      factor(levels_col[ imputed_data_BOOT[[col]][, 5L] ], levels = levels_col)
  } else {
    data_imputed_AREG_test[[col]][is.na(data[[col]])] <- imputed_data_BOOT[[col]][, 5L]
  }
}
```

```{r}
density_before_after(data, data_imputed_AREG_test)
```


```{r}
mass_before_after(data, data_imputed_AREG_test)
```

```{r}
save(data_imputed_AREG_test, file = "C:/Users/Asus/Desktop/Quarto/Mineria_de_Datos/Treball_Mineria_de_Dades/Bases_de_dades/data_NA_imputed_AREG_test.RData")
```



