---
title: "Imputation for the test file"
author: "Arnau Gómez Català"
date: "2025-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(VIM)
library(mice)
library(missForest)
library(Hmisc)

# 1. CARREGAR DADES
data <- read_csv("test.csv", col_types = cols(...1 = col_skip()))

# --- CANVI 1: SELECCIÓ DE VARIABLES IMPORTANTS (Igual que Train però sense Exited) ---
vars_bones <- c("ID", "Surname", # Identificadors
                "CreditScore", "Geography", "Gender", "Age", "Tenure", 
                "Balance", "NumOfProducts", "HasCrCard", "IsActiveMember", 
                "EstimatedSalary")

# Filtrem
data <- data %>% select(any_of(vars_bones))
# ------------------------------------------------

# 2. CONVERSIÓ FACTORS
for(i in 1:ncol(data)){
  if(is.character(data[[i]])==TRUE){
    data[[i]] = as.factor(data[[i]])
  }
}

data$HasCrCard <- as.factor(data$HasCrCard)
data$IsActiveMember <- as.factor(data$IsActiveMember)
# (SavingsAccountFlag i Exited ja no hi són o no es posen)
```

```{r}
visdat::vis_dat(data)
```

```{r}
summary(data)
```

```{r}
naniar::mcar_test(data)
```

## MICE:


```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
## MICE: IMPUTACIÓ CONJUNTA

# 1. Selecció variables (Sense ID/Surname)
data_mice_input <- data |>
  select(Tenure, Balance, Age, NumOfProducts, EstimatedSalary, CreditScore, 
         Geography, Gender, HasCrCard, IsActiveMember)

# 2. Execució MICE
set.seed(28657)
mice_output <- mice::mice(data_mice_input, m = 10, maxit = 10, seed = 28657)

# 3. Completar
imputed_data_MICE <- mice::complete(mice_output)

# 4. Reconstruir amb IDs
data_imputed_MICE_test <- data
for(col in names(imputed_data_MICE)) {
  data_imputed_MICE_test[[col]] <- imputed_data_MICE[[col]]
}

save(data_imputed_MICE_test, file = "data_NA_imputed_MICE_test.RData")
```


```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
density_before_after <- function(before, after) {
    require(ggplot2)
    
    density_df_before <- before |> 
        select(where(is.numeric)) |>
        mutate(imputation = "original")
    
    density_df_after <- after |>
        select(where(is.numeric)) |>
        mutate(imputation = "imputat")
    
    density_df <- bind_rows(density_df_before, density_df_after) |>
        mutate(imputation = factor(imputation)) |>
        tidyr::pivot_longer(!imputation, names_to = "variable") |>
        filter(!is.na(value))
    
    ggplot(density_df, aes(x = value, color = imputation, fill = imputation)) +
        facet_wrap(~variable, scales = "free") +
        geom_histogram(alpha = 0.2, width = 0.1, bins = 30, position = "dodge") +
        scale_color_discrete(aesthetics = c("color", "fill"), name = "") +
        scale_y_continuous(breaks = NULL) +
        xlab("") +
        ylab("") +
        ggtitle("Densitat abans i després de la imputació.") +
        theme_minimal() +
        theme(panel.grid = element_blank())
}
```


```{r}
density_before_after(data, data_imputed_MICE_test)
```


## KNN:

```{r}
# 1. Preparem dades
data_knn_input <- data |>
  select(Tenure, Balance, Age, NumOfProducts, EstimatedSalary, CreditScore, 
         Geography, Gender, HasCrCard, IsActiveMember)

# 2. Executem KNN
set.seed(28657)
imputed_data_KNN_raw <- VIM::kNN(
    as.data.frame(data_knn_input), 
    k = 7, 
    imp_var = FALSE
)

# 3. Reconstruïm
data_imputed_KNN_test <- imputed_data_KNN_raw
data_imputed_KNN_test$ID <- data$ID
data_imputed_KNN_test$Surname <- data$Surname

data_imputed_KNN_test <- data_imputed_KNN_test %>% select(ID, Surname, everything())

save(data_imputed_KNN_test, file = "data_NA_imputed_KNN_test.RData")
```


```{r}
density_before_after(data, data_imputed_KNN_test)
```


## Random FOREST:

```{r, results=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
set.seed(28657)

# Usem el mateix input net que pel KNN
forest_output <- missForest::missForest(
    as.data.frame(data_knn_input), 
    maxiter = 10, ntree = 20,
    variablewise = TRUE, verbose = TRUE 
)

# Reconstruïm
data_imputed_FOREST_test <- forest_output$ximp
data_imputed_FOREST_test$ID <- data$ID
data_imputed_FOREST_test$Surname <- data$Surname

save(data_imputed_FOREST_test, file = "data_NA_imputed_FOREST_test.RData")
```

```{r}
density_before_after(data, data_imputed_FOREST_test)
```

```{r}
# Taula d'error OOB (Molt útil pel report)
bind_cols(
    variable = names(forest_output$ximp),
    tipus_error = names(forest_output$OOBerror),
    error = round(forest_output$OOBerror, 2)
) |>
    arrange(tipus_error, -error) |>
    knitr::kable(col.names = c("Variable", "Tipus d'Error", "Error"))
```

## Imputació per Bootstrap:

Amb la funció *aregImpute()* podrem fer imputació de les dades faltants basada en regressions amb splines. Utilitza regressió aditiva amb splines per a variables numèriques i regressió logística per a les categòriques.

```{r, results=FALSE, message=FALSE, warning=FALSE, echo=TRUE, include=FALSE}
# 1. Preparació (DF + Factors + Sense Exited)
data_areg_input <- as.data.frame(data) |>
  select(Tenure, Balance, Age, NumOfProducts, EstimatedSalary, CreditScore, 
         Geography, Gender, HasCrCard, IsActiveMember)

data_areg_input$NumOfProducts <- as.factor(data_areg_input$NumOfProducts)
data_areg_input <- droplevels(data_areg_input)

set.seed(28657)

# 2. Execució AREG (Sense Exited a la fórmula)
areg_output <- Hmisc::aregImpute(
    data = data_areg_input,
    formula = ~ Gender + HasCrCard + IsActiveMember + Geography + 
                Tenure + Balance + Age + EstimatedSalary + CreditScore + NumOfProducts,
    n.impute = 5,
    nk = 5, # Important
    match = 'closest'
)

# 3. Reconstrucció
imputed_values_list <- areg_output$imputed
data_imputed_AREG_test <- data 

for (col in names(imputed_values_list)) {
  if (!is.null(imputed_values_list[[col]])) {
    vals_imputats <- imputed_values_list[[col]][, 3] 
    
    if (is.factor(data_imputed_AREG_test[[col]])) {
       levels_col <- levels(data_areg_input[[col]])
       data_imputed_AREG_test[[col]][is.na(data_imputed_AREG_test[[col]])] <- 
         levels_col[vals_imputats]
    } else {
       data_imputed_AREG_test[[col]][is.na(data_imputed_AREG_test[[col]])] <- vals_imputats
    }
  }
}

save(data_imputed_AREG_test, file = "data_NA_imputed_AREG_test.RData")
```


```{r}
density_before_after(data, data_imputed_AREG_test)
```



